### PR TITLE
Fix error messages

### LINKED ISSUE #137: [PE-D][Tester A] BUG - Incorrect error message when adding a negative number in phone
It might be better to state that the phone number should be valid or the phone number should only contain positive numbers instead of just numbers because user might enter a negative number by accident. 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Ugholaf/ped#3

### LINKED ISSUE #138: [PE-D][Tester C] Typo in event -a usage message
Very minor nitpick, but the error message explaining the usage of the `event -a` command has also has no line break (or space) before the list of Parameters like most other commands.

Steps to reproduce: run `event -a` with no further arguments

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: teekaytai/ped#3

### LINKED ISSUE #140: [PE-D][Tester D] Command event -u not displaying events on the same day.
I understand that in the user guide, it is stated that events on the same day will not be displayed with the event -u command. However, this behavior seems a little strange. If the time now is 4.30pm, and I have an event later in the day at 9.00pm, it seems logical for this event to appear. When I tested this, it does not show however. As such I feel this might be a feature flaw.

elk eating contest is not shown

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tin-jy/ped#1

### LINKED ISSUE #145: [PE-D][Tester A] BUG - Profile edit command unable to handle extremely large number
This error message is correct as the app does not have that many people.

However, when the `INDEX` gets larger, it gives the wrong error message.

The above command fits the command format but there is still an error message saying it is not the correct command format. 

The app should handle large indexes properly if the app is unable to support a number of profiles larger than a certain value, a different error message should be given to inform the user to delete some of the current profiles and make space for the new ones when the app has reached the maximum profiles it can store. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Ugholaf/ped#6

### PR DESCRIPTION
**Pull request by KSHan29**
- [x] Specify phone numbers to only contain numeric characters - Closes #137 
- [x] Add `\n` to `profile -a` and `event -a` invalid format messages - Closes #138
- [x] Set limit for Index to positive numbers less than 10,000 (Continues to display invalid command format but edited message for all index commands to specify requirements of index) - Closes #145 
- [x] For `ViewUpcomingEventsCommand` I think might not be able to edit due to feature freeze so I instead edited documentation to at least specify clearly what the command can do. - Closes #140,  #153,  #154, #158, #165

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -23,7 +23,9 @@
  */
 public class ParserUtil {
     public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
+    public static final String MESSAGE_INDEX_TOO_LONG = "Index provided must be no longer than 4 characters";
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:26]: perhaps you can explain here that NUScheduler only supports up to 9999 entries. good to mention in UG as well

File: src/main/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommand.java [hunk 2]
```diff
@@ -16,11 +16,11 @@
 public class ViewUpcomingEventsCommand extends EventCommand {
     public static final String COMMAND_OPTION = "u";
 
-    public static final String MESSAGE_HELP = "Lists upcoming events in NUScheduler for the next specified "
+    public static final String MESSAGE_HELP = "Lists upcoming events in NUScheduler starting in the next specified "
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommand.java:19]: I feel like this phrasing may not be clear enough. perhaps you could elaborate like so "i.e. events starting today will not be included"

File: src/main/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommand.java [hunk 3]
```diff
@@ -30,8 +30,8 @@ public class ViewUpcomingEventsCommand extends EventCommand {
     public static final String MESSAGE_SUCCESS_UPCOMING_DAYS = "in the next %1$s days!";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + " " + PREFIX_OPTION + COMMAND_OPTION
-            + ": Lists the events that are occurring in the next specified days.\n"
-            + "Parameters: DAYS (must be a positive integer)\n"
+            + ": Lists the upcoming events that are starting in the next specified days.\n"
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommand.java:33]: similar to previous comment

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -153,6 +158,9 @@ public static DateTime parseDateTime(String dateTime) throws ParseException {
     public static int parseDays(String days) throws ParseException {
         requireNonNull(days);
         String trimmedDays = days.trim();
+        if (days.length() > 4) {
```
Comment (lesterong) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:161]: Should this be `trimmedDays` instead?

**Review by lesterong — COMMENTED** [review]
Just one minor nit, otherwise good job!

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (KSHan29) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:26]: For this error message, it does not get displayed to users as it will be caught in the respective command parsers and the error message shown will be invalid command format.

Maybe for this I will add into the section `Notes about the command format` to explain that only up to 9999 entries is supported which sufficiently meets the needs of most NUS students?

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 4 above)
Comment (KSHan29) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:161]: Yup, thanks!

File: docs/UserGuide.md [hunk 5]
```diff
@@ -244,6 +248,14 @@ Format: `event -u DAYS`
 * The days refer to the number of days after the current date. All events that start within this time frame will be displayed. Events occurring on the day the command is entered will not be displayed.
 * The days **must be a positive integer less than 10000** 1, 2, 3, …​, 9999.
```
Comment (lesterong) [inline docs/UserGuide.md:249]: Perhaps you're missing a `e.g.` here as well

File: docs/UserGuide.md [hunk 6]
```diff
@@ -244,6 +248,14 @@ Format: `event -u DAYS`
...
 
+<div markdown="block" class="alert alert-info">
+
+**:information_source: Notes about usage:**<br>
+
+DAYS entered is limited to 9999 days as this sufficiently covers the usage for most NUS students.
```
Comment (lesterong) [inline docs/UserGuide.md:255]: Minor, but maybe a bullet point can be added here to keep it more in line with the other notes block

File: docs/UserGuide.md [hunk 7]
```diff
@@ -53,7 +53,11 @@ With NUScheduler, you can store the contact details of the NUS community around
   e.g. `[t/TAG]…​` can be used as ` ` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
   e.g. `pr/PROFILE_INDEX...` must be used at least once, such as `pr/1`, `pr/3 pr/5` etc.
 
-* For Event and Profile commands, option flags (-x where x is a placeholder for valid flags e.g. a, d, v) must be used after the event and profile command word.
+* For `Event` and `Profile` commands, option flags (-x where x is a placeholder for valid flags e.g. a, d, v) must be used after the `event` and `profile` command word.
+
+* For `Event` and `Profile` commands which require an `Index`, the `Index` must be provided after the option flag. <br>
```
Comment (lesterong) [inline docs/UserGuide.md:58]: Minor, but I think there's no need for a `<br>` tag here

File: docs/UserGuide.md [hunk 8]
```diff
@@ -53,7 +53,11 @@ With NUScheduler, you can store the contact details of the NUS community around
...
+
+* In addition, the `Index` provided must be a positive number less than 10000 as `NUScheduler` is designed to handle a maximum of 9999 entries for `Profile`s and `Event`s which covers the needs for most NUS students.
```
Comment (lesterong) [inline docs/UserGuide.md:60]: Perhaps we don't need the back ticks for NUScheduler to keep it in line with the formatting of NUScheduler throughout our user guide.

File: docs/UserGuide.md [hunk 9]
```diff
@@ -281,16 +281,21 @@ Displays a list of upcoming events, ordered by the date, which starts in the nex
...
 
 <div markdown="block" class="alert alert-info">
 
 **:information_source: Notes about usage:**<br>
 
-DAYS entered is limited to 9999 days as this sufficiently covers the usage for most NUS students.
+* DAYS entered is limited to 9999 days as this sufficiently covers the usage for most NUS students.
 
 </div>
+=======
```
Comment (lesterong) [inline docs/UserGuide.md:295]: Seems like you accidentally missed out these from the merge conflict. There's a few more below as well!

**Review by lesterong — COMMENTED** [review]
Seems like there's some remains from the merge conflict!\, otherwise looks good.

File: docs/UserGuide.md (hunk 9 above)
Comment (KSHan29) [reply docs/UserGuide.md]: Thanks for the catch! :')

File: docs/UserGuide.md [hunk 10]
```diff
@@ -474,13 +486,21 @@ Example:
...
-* `@u.nus.edu`
-* `@u.duke.nus.edu`
-* `@nus.edu.sg`
-* `@comp.nus.edu.sg`
-* `@u.yale-nus.edu.sg`
+  * `@u.nus.edu`
+  * `@u.duke.nus.edu`
+  * `@nus.edu.sg`
+  * `@comp.nus.edu.sg`
+  * `@u.yale-nus.edu.sg`
```
Comment (lesterong) [inline docs/UserGuide.md:503]: Maybe can remove the `@` over here since you mentioned it's after `@`

File: docs/UserGuide.md [hunk 11]
```diff
@@ -474,13 +486,21 @@ Example:
...
-NUScheduler checks the emails of your profiles against a list of valid NUS email domains.
+NUScheduler checks the following:
+
+* Local part (the characters in your email before `@`) of the emails must follow these rules: 
+
+  * Only alphanumeric characters and these special characters, `+`, `_`, `.`, `-` are allowed
+  * The local part cannot start or end with a special character
+  * The local part must begin and end with an alphabet or number 
+
+* Domain (the characters in your email after `@`) of the emails must be one of the following valid NUS email domains.
```
Comment (lesterong) [inline docs/UserGuide.md:497]:
```suggestion
* Domain (the characters in your email after `@`) of the emails must be one of the following valid NUS email domains:

**Review by lesterong — APPROVED** [review]

File: docs/UserGuide.md [hunk 12]
```diff
@@ -100,7 +100,11 @@ The following is the main user interface of NUScheduler.
   e.g. `[t/TAG]…​` can be used as ` ` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
   e.g. `pr/PROFILE_INDEX…​` must be used at least once, such as `pr/1`, `pr/3 pr/5` etc.
 
-* For Event and Profile commands, option flags (-x where x is a placeholder for valid flags e.g. a, d, v) must be used after the event and profile command word.
+* For `Event` and `Profile` commands, option flags (-x where x is a placeholder for valid flags e.g. a, d, v) must be used after the `event` and `profile` command word.
+
+* For `Event` and `Profile` commands which require an `Index`, the `Index` must be provided after the option flag.
```
Comment (ichigh0st) [inline docs/UserGuide.md:105]:
```suggestion
* For `Event` and `Profile` commands which require an `INDEX`, the `INDEX` must be provided after the option flag.
```

File: docs/UserGuide.md [hunk 13]
```diff
@@ -100,7 +100,11 @@ The following is the main user interface of NUScheduler.
...
+
+* In addition, the `Index` provided must be a positive number less than 10000 as NUScheduler is designed to handle a maximum of 9999 entries for `Profile`s and `Event`s which covers the needs for most NUS students.
```
Comment (ichigh0st) [inline docs/UserGuide.md:107]:
```suggestion
* In addition, the `INDEX` provided must be a positive number less than 10000 as NUScheduler is designed to handle a maximum of 9999 entries for `Profile`s and `Event`s which covers the needs for most NUS students.
```

File: docs/UserGuide.md [hunk 14]
```diff
@@ -279,12 +283,20 @@ Note how the first and third attendee under the first listed event `Discuss pres
...
 #### Viewing upcoming events: `event -u`
 
-Displays a list of upcoming events, ordered by the date, for the next specified number of days.
+Displays a list of upcoming events, ordered by the date, which starts in the next specified number of days.
 
 Format: `event -u DAYS`
 
-* The days refer to the number of days from the current date. All events within this time frame will be displayed. Events occurring on the day the command is entered will not be displayed.
-* The days **must be a positive integer** 1, 2, 3, …​
+* The days refer to the number of days after the current date. All events that start within this time frame will be displayed. Events occurring on the day the command is entered will not be displayed.
```
Comment (ichigh0st) [inline docs/UserGuide.md:290]:
```suggestion
* The days refer to the number of days after the current date. All events that start within this time frame will be displayed. Events starting and occurring on the day the command is entered will not be displayed.
```

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 15]
```diff
@@ -32,6 +34,9 @@ public class ParserUtil {
      */
     public static Index parseIndex(String oneBasedIndex) throws ParseException {
         String trimmedIndex = oneBasedIndex.trim();
+        if (trimmedIndex.length() > 4) {
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:37]: I realised that checking for the length may not be very ideal.
Previously, if the user enters `profile -d 00001`, the first profile is deleted. however now it shows an error as even though the number is valid it is greater than 5 characters. would it be better to use parseInt or parseLong and check whether it is `< 10000`?

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 16]
```diff
@@ -153,6 +158,9 @@ public static DateTime parseDateTime(String dateTime) throws ParseException {
     public static int parseDays(String days) throws ParseException {
         requireNonNull(days);
         String trimmedDays = days.trim();
+        if (trimmedDays.length() > 4) {
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:161]: similar issue as previous

File: docs/UserGuide.md [hunk 17]
```diff
@@ -474,13 +486,21 @@ Example:
 
 ### Accepted email formats
 
-NUScheduler checks the emails of your profiles against a list of valid NUS email domains.
+NUScheduler checks the following:
+
+* Local part (the characters in your email before `@`) of the emails must follow these rules: 
+
+  * Only alphanumeric characters and these special characters, `+`, `_`, `.`, `-` are allowed
```
Comment (ichigh0st) [inline docs/UserGuide.md:493]: I might be wrong but they can't be consecutive as well right, or are you doing this in another pr

**Review by ichigh0st — CHANGES_REQUESTED** [review]

File: docs/UserGuide.md (hunk 17 above)
Comment (lesterong) [reply docs/UserGuide.md:493]: You're right that the special characters cannot be consecutive in the current regex, I think we are not changing it since it is possibly an enhancement rather than a bug fix.

Comment (KSHan29) [reply docs/UserGuide.md:493]: Yup, good catch! I will add it in

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 15 above)
Comment (KSHan29) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: I updated the method to correct this. Please help to test again thanks! Also updated the methods and documentation to limit `INDEX` to 1000.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 18]
```diff
@@ -156,6 +169,13 @@ public static int parseDays(String days) throws ParseException {
...
             throw new ParseException(MESSAGE_INVALID_DAYS);
         }
+
+        int index = Integer.parseInt(trimmedDays);
+
+        // limits days to 9999
+        if (index > MAX_DAYS) {
+            throw new ParseException(MESSAGE_DAYS_GREATER_THAN_MAX);
+        }
         return Integer.parseInt(trimmedDays);
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:179]:
```suggestion
        return index;
```

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 19]
```diff
@@ -22,19 +22,32 @@
...
         }
+
+        int index = Integer.parseInt(trimmedIndex);
+
+        // limits index to 9999
+        if (index > MAX_INDEX) {
+            throw new ParseException(MESSAGE_INDEX_GREATER_THAN_MAX);
+        }
+
         return Index.fromOneBased(Integer.parseInt(trimmedIndex));
```
Comment (ichigh0st) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:51]:
```suggestion
        return Index.fromOneBased(index);
```

**Review by ichigh0st — APPROVED** [review]
nice!! just one minor issue with the code left to fix!
